import 'package:bookflix/home/bloc/HomePageState.dart';
import 'package:bookflix/models.dart';
import 'package:http/http.dart' as http;
import 'dart:convert' as converter;
import 'dart:async';

class Repositoty {
  final String baseUrl = "https://www.googleapis.com/books/v1/volumes";

  Future<HomePageState> getItems(String query) async {
    final url = "$baseUrl?=$query";
    var response = http.get(url);
    if (response.statusCode == 200) {
      var body = response.body;
      var json = converter.jsonDecode(body);
      var data = Autogenerated.fromJson(json);
      var items = data.items;
      return HomePageStateSuccess(items: items);
    } else {
      return HomePageStateError(message: "falha de internet");
    }
  }
}
